"""Deployment — turn a config + task into something running, from the CLI.

Two paths, both honest about credentials (secrets are never baked into an image
or a manifest — they are referenced as environment variables the platform
injects at deploy time):

* **local** — generate a project Dockerfile (pip-installs ``zu-runtime``, copies
  the config), build it, and run ``zu serve`` in a container, passing the
  provider's key env through. One command to a running, streamable agent.
* **manifests** — emit a Dockerfile / docker-compose / Fly / Render config you
  apply with your platform's own tooling (we don't hold your cloud creds).

The generated artifacts are deterministic text, so the manifest path needs no
Docker and is fully testable; only ``local`` touches the daemon.
"""

from __future__ import annotations

import os
from typing import Any

TARGETS = ("local", "dockerfile", "compose", "fly", "render")

# Env vars worth passing through to a container / referencing in a manifest.
_KEY_ENVS = (
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
    "OPENAI_BASE_URL",
    "OPENROUTER_API_KEY",
    "OPENROUTER_BASE_URL",
)


def dockerfile_text(config: str, *, extras: str = "all", port: int = 8000) -> str:
    return (
        "# Generated by `zu deploy`. Runs your agent as an HTTP service.\n"
        "# Secrets are NOT baked in — pass them at run time (-e ANTHROPIC_API_KEY=...).\n"
        "FROM python:3.11-slim\n"
        "ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1\n"
        f'RUN pip install "zu-runtime[{extras}]"\n'
        "WORKDIR /app\n"
        f"COPY {config} ./{config}\n"
        f"EXPOSE {port}\n"
        f'CMD ["zu", "serve", "-c", "{config}", "--host", "0.0.0.0", "--port", "{port}"]\n'
    )


def compose_text(name: str, config: str, *, port: int = 8000) -> str:
    env_lines = "\n".join(f"      - {k}" for k in _KEY_ENVS)
    return (
        "# Generated by `zu deploy compose`. Secrets pass through from your shell\n"
        "# (export them, or use an env_file). `docker compose up --build`.\n"
        "services:\n"
        f"  {name}:\n"
        "    build: .\n"
        f'    ports: ["{port}:{port}"]\n'
        "    environment:\n"
        f"{env_lines}\n"
        "    restart: unless-stopped\n"
    )


def fly_text(name: str, *, port: int = 8000) -> str:
    return (
        "# Generated by `zu deploy fly`. Then: fly launch --no-deploy (once),\n"
        "# fly secrets set ANTHROPIC_API_KEY=... , fly deploy.\n"
        f'app = "{name}"\n\n'
        "[build]\n\n"
        "[http_service]\n"
        f"  internal_port = {port}\n"
        "  force_https = true\n"
        "  auto_stop_machines = true\n"
        "  min_machines_running = 0\n\n"
        "[[vm]]\n"
        '  memory = "512mb"\n'
        "  cpus = 1\n"
    )


def render_text(name: str, *, port: int = 8000) -> str:
    env_lines = "\n".join(f"      - key: {k}\n        sync: false" for k in _KEY_ENVS)
    return (
        "# Generated by `zu deploy render`. Commit, then create a Blueprint on Render.\n"
        "services:\n"
        "  - type: web\n"
        f"    name: {name}\n"
        "    runtime: docker\n"
        "    dockerfilePath: ./Dockerfile\n"
        "    envVars:\n"
        f"{env_lines}\n"
    )


def write_dockerfile(directory: str, config: str, *, extras: str, port: int, force: bool) -> str:
    path = os.path.join(directory, "Dockerfile")
    if os.path.exists(path) and not force:
        return path  # respect an existing Dockerfile (e.g. a hand-tuned one)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(dockerfile_text(config, extras=extras, port=port))
    return path


def generate(target: str, directory: str, *, name: str, config: str, extras: str, port: int, force: bool) -> list[str]:
    """Write the manifest(s) for a non-local target. Returns the paths written."""
    written: list[str] = [write_dockerfile(directory, config, extras=extras, port=port, force=True)]
    files: dict[str, str] = {}
    if target == "dockerfile":
        pass  # the Dockerfile above is the whole artifact
    elif target == "compose":
        files["docker-compose.yml"] = compose_text(name, config, port=port)
    elif target == "fly":
        files["fly.toml"] = fly_text(name, port=port)
    elif target == "render":
        files["render.yaml"] = render_text(name, port=port)
    for fname, content in files.items():
        path = os.path.join(directory, fname)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(path)
    return written


def local_commands(name: str, config: str, *, port: int) -> tuple[list[str], list[str]]:
    """The (build, run) docker command lines for a local deploy. The run command
    passes through whichever provider key envs are actually set, so no secret is
    ever written to a file or the image."""
    build = ["docker", "build", "-t", name, "."]
    run = ["docker", "run", "-d", "--name", name, "-p", f"{port}:{port}"]
    for key in _KEY_ENVS:
        if os.environ.get(key):
            run += ["-e", key]
    run.append(name)
    return build, run
