"""Deployment — turn a config + task into something running, from the CLI.

Two paths, both honest about credentials (secrets are never baked into an image
or a manifest — they are referenced as environment variables the platform
injects at deploy time):

* **local** — generate a project Dockerfile (pip-installs ``zu-runtime``, copies
  the config), build it, and run ``zu serve`` in a container, passing the
  provider's key env through. One command to a running, streamable agent.
* **manifests** — emit a Dockerfile / docker-compose / Fly / Render config you
  apply with your platform's own tooling (we don't hold your cloud creds).

The generated artifacts are deterministic text, so the manifest path needs no
Docker and is fully testable; only ``local`` touches the daemon.
"""

from __future__ import annotations

import os

TARGETS = ("local", "dockerfile", "compose", "fly", "render")

# Env vars worth passing through to a container / referencing in a manifest.
# Provider key/base-url envs plus ZU_SERVE_TOKEN (the bearer token `zu serve`
# requires when bound to a non-localhost host — see server.py). A config that
# names a *different* key env (a custom provider) has it added on top by
# ``key_envs_for_config`` below, so the passthrough isn't limited to these.
_KEY_ENVS = (
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
    "OPENAI_BASE_URL",
    "OPENROUTER_API_KEY",
    "OPENROUTER_BASE_URL",
    "ZU_SERVE_TOKEN",
)


def key_envs_for_config(cfg: object | None) -> tuple[str, ...]:
    """The env vars to pass through for ``cfg``: the defaults above plus any
    ``api_key_env`` / ``base_url_env`` the config's provider(s) actually name —
    so a custom provider reading e.g. ``GROQ_API_KEY`` is credentialled in the
    deployed container instead of silently starting without a key. Order is
    stable (defaults first, then config-declared extras) and de-duplicated."""
    envs: list[str] = list(_KEY_ENVS)
    provider = getattr(cfg, "provider", None)
    providers = list(getattr(cfg, "providers", {}).values()) if cfg is not None else []
    for p in [provider, *providers]:
        for attr in ("api_key_env", "base_url_env"):
            val = getattr(p, attr, None)
            if isinstance(val, str) and val and val not in envs:
                envs.append(val)
    return tuple(envs)


def dockerfile_text(
    config: str, *, extras: str = "all", port: int = 8000,
    python_version: str = "3.11", version: str | None = None,
) -> str:
    # Pin the runtime version when known, so a rebuilt image is reproducible
    # rather than silently pulling a newer (possibly breaking) release. The
    # Python base is configurable for the same reason — a pinned, deliberate base.
    spec = f"zu-runtime[{extras}]" + (f"=={version}" if version else "")
    return (
        "# Generated by `zu deploy`. Runs your agent as an HTTP service.\n"
        "# Secrets are NOT baked in — pass them at run time (-e ANTHROPIC_API_KEY=...).\n"
        f"FROM python:{python_version}-slim\n"
        "ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1\n"
        f'RUN pip install "{spec}"\n'
        "WORKDIR /app\n"
        f"COPY {config} ./{config}\n"
        f"EXPOSE {port}\n"
        f'CMD ["zu", "serve", "-c", "{config}", "--host", "0.0.0.0", "--port", "{port}"]\n'
    )


def pack_dockerfile_text(base: str = "zu:latest", *, agent: str = "agent.yaml") -> str:
    """A Dockerfile that BAKES a bundle (its ``agent.yaml`` + ``tools/`` + a
    ``requirements.txt``) into a standalone image, FROM a Zu runtime ``base``.

    Unlike ``--sandboxed`` (which mounts the bundle and so is limited to the base
    image's packages), pack installs the bundle's own pip deps at build time — so
    a bundle whose tools need extra libraries runs anywhere. Secrets are NOT
    baked: pass them at run time (``-e ANTHROPIC_API_KEY=...``). The bundle is on
    ``PYTHONPATH`` so its ``tools.x:Class`` import-refs resolve; the image runs as
    the base's non-root user."""
    return (
        "# Generated by `zu pack`. Bakes this bundle into a standalone image.\n"
        "# Secrets are NOT baked — pass them at run time (-e ANTHROPIC_API_KEY=...).\n"
        f"FROM {base}\n"
        "USER root\n"
        "WORKDIR /agent\n"
        "COPY . /agent\n"
        "RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi\n"
        "ENV PYTHONPATH=/agent\n"
        "RUN chown -R 10001:10001 /agent 2>/dev/null || true\n"
        "USER 10001\n"
        f'CMD ["zu", "run", "/agent/{agent}"]\n'
    )


def pack_build_command(tag: str, bundle: str) -> list[str]:
    """The ``docker build`` argv for ``zu pack``. The Dockerfile is fed on stdin
    (``-f -``) with the bundle as the build context, so packing never writes a
    file into the user's bundle directory."""
    return ["docker", "build", "-t", tag, "-f", "-", bundle]


def compose_text(name: str, config: str, *, port: int = 8000, envs: tuple[str, ...] = _KEY_ENVS) -> str:
    env_lines = "\n".join(f"      - {k}" for k in envs)
    return (
        "# Generated by `zu deploy compose`. Secrets pass through from your shell\n"
        "# (export them, or use an env_file). `docker compose up --build`.\n"
        "services:\n"
        f"  {name}:\n"
        "    build: .\n"
        f'    ports: ["{port}:{port}"]\n'
        "    environment:\n"
        f"{env_lines}\n"
        "    restart: unless-stopped\n"
    )


def fly_text(name: str, *, port: int = 8000) -> str:
    return (
        "# Generated by `zu deploy fly`. Then: fly launch --no-deploy (once),\n"
        "# fly secrets set ANTHROPIC_API_KEY=... , fly deploy.\n"
        f'app = "{name}"\n\n'
        "[build]\n\n"
        "[http_service]\n"
        f"  internal_port = {port}\n"
        "  force_https = true\n"
        "  auto_stop_machines = true\n"
        "  min_machines_running = 0\n\n"
        "[[vm]]\n"
        '  memory = "512mb"\n'
        "  cpus = 1\n"
    )


def render_text(name: str, *, port: int = 8000, envs: tuple[str, ...] = _KEY_ENVS) -> str:
    env_lines = "\n".join(f"      - key: {k}\n        sync: false" for k in envs)
    return (
        "# Generated by `zu deploy render`. Commit, then create a Blueprint on Render.\n"
        "services:\n"
        "  - type: web\n"
        f"    name: {name}\n"
        "    runtime: docker\n"
        "    dockerfilePath: ./Dockerfile\n"
        "    envVars:\n"
        f"{env_lines}\n"
    )


def write_dockerfile(
    directory: str, config: str, *, extras: str, port: int, force: bool,
    python_version: str = "3.11", version: str | None = None,
) -> str:
    path = os.path.join(directory, "Dockerfile")
    if os.path.exists(path) and not force:
        return path  # respect an existing Dockerfile (e.g. a hand-tuned one)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(dockerfile_text(
            config, extras=extras, port=port, python_version=python_version, version=version,
        ))
    return path


def generate(
    target: str, directory: str, *, name: str, config: str, extras: str, port: int, force: bool,
    python_version: str = "3.11", version: str | None = None,
    envs: tuple[str, ...] = _KEY_ENVS,
) -> list[str]:
    """Write the manifest(s) for a non-local target. Returns the paths written."""
    written: list[str] = [write_dockerfile(
        directory, config, extras=extras, port=port, force=True,
        python_version=python_version, version=version,
    )]
    files: dict[str, str] = {}
    if target == "dockerfile":
        pass  # the Dockerfile above is the whole artifact
    elif target == "compose":
        files["docker-compose.yml"] = compose_text(name, config, port=port, envs=envs)
    elif target == "fly":
        files["fly.toml"] = fly_text(name, port=port)
    elif target == "render":
        files["render.yaml"] = render_text(name, port=port, envs=envs)
    for fname, content in files.items():
        path = os.path.join(directory, fname)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        written.append(path)
    return written


def local_commands(
    name: str, config: str, *, port: int, envs: tuple[str, ...] = _KEY_ENVS
) -> tuple[list[str], list[str]]:
    """The (build, run) docker command lines for a local deploy. The run command
    passes through whichever of ``envs`` are actually set, so no secret is ever
    written to a file or the image."""
    build = ["docker", "build", "-t", name, "."]
    run = ["docker", "run", "-d", "--name", name, "-p", f"{port}:{port}"]
    for key in envs:
        if os.environ.get(key):
            run += ["-e", key]
    run.append(name)
    return build, run
