"""Zu core — the small, stable runtime: contracts, ports, registry, loop, bus.

Depends only on the standard library and Pydantic. It contains no model SDK,
no domain branching, and no knowledge of any specific tool or provider.
"""

from __future__ import annotations

from . import events
from .bus import EventBus, SubscriberFailure
from .capabilities import (
    Capability,
    LibrarySurface,
    __version__,
    capabilities,
    library_surface,
    provenance,
)
from .chain import chain_head, event_digest, link, verify_against_anchor, verify_chain
from .codec import IdentityCodec, KeyProvider, PayloadCodec, decode_payload, encode_payload
from .content import Action, Audio, Content, ContentPart, Image, Observation, Text
from .content_view import (
    WANT_DIAGNOSTIC,
    WANT_FULL,
    ContentUnit,
    ContentView,
    FieldState,
    Provenance,
    TrustedFrame,
    Want,
    project,
)
from .contracts import Budget, Event, Result, Status, TaskSpec
from .effect import is_noop, surface_diff
from .escalation import ProblemContext, Repair
from .events import (
    CHECKPOINT_MARKED,
    CONTENT_CAPTURED,
    RUN_ROLLED_BACK,
    STEP_ESCALATED,
    STEP_REPAIRED,
)
from .eventstore import (
    ALLOWED_EVENT_FILTERS,
    allowed_filters,
    event_matches,
    register_event_filter,
    validate_filter,
)
from .loop import last_known_good, mark_checkpoint, rollback_and_replan
from .monitors import evaluate_invariants, run_monitors
from .ports import (
    CAP_FS_READ,
    CAP_FS_WRITE,
    CAP_NET,
    CAP_SANDBOX,
    CAP_SUBPROCESS,
    EGRESS_OPEN,
    INTERFACE_ATTR,
    INTERFACE_VERSION,
    Candidate,
    Capabilities,
    CapScope,
    Channel,
    ChannelRequest,
    ChannelResponse,
    Consent,
    CredentialBroker,
    Detector,
    EgressEnforcement,
    EventSink,
    ExecutionLedger,
    Finish,
    Grant,
    GrantStore,
    IdentityProof,
    Instrument,
    InvocationGate,
    ModelProvider,
    ModelRequest,
    ModelResponse,
    Policy,
    ReplayArbiter,
    ReplayDecision,
    ReputationProvider,
    ReputationVerdict,
    RetrievalProvider,
    RetrievalQuery,
    RunContext,
    SandboxBackend,
    Scope,
    Severity,
    Tool,
    ToolCall,
    ToolSpec,
    Trigger,
    TriggerEvent,
    UseOutcome,
    UseRequest,
    Validator,
    Verdict,
    WorkloadIdentity,
    declared_envelope,
)
from .projections import SessionState, SessionStore
from .registry import (
    REGISTRY,
    IncompatibleInterfaceError,
    KindSpec,
    LoadFailure,
    Registry,
    arbiter,
    backend,
    channel,
    check_interface,
    credential_broker,
    detector,
    gate,
    kind_decorator,
    policy,
    provider,
    reputation_provider,
    retrieval_provider,
    sink,
    tool,
    trigger,
    validator,
)
from .security import SecurityBlock
from .sinks import MemoryEventSink
from .view import RENDER_KEYS, scope_event, scope_payload

__all__ = [
    # capability surface + provenance (issue #30) — what Zu provides, here
    "__version__",
    "provenance",
    "capabilities",
    "Capability",
    "library_surface",
    "LibrarySurface",
    # contracts
    "Budget",
    "Event",
    "Result",
    "Status",
    "TaskSpec",
    # multimodal content (the policy currency)
    "Content",
    "ContentPart",
    "Text",
    "Image",
    "Audio",
    "Observation",
    "Action",
    # content_view — the reading projection (Issue #41): types, trust boundary,
    # want= scoping, the only door to a model (TrustedFrame), shared escalation types
    "Provenance",
    "ContentUnit",
    "FieldState",
    "ContentView",
    "Want",
    "WANT_DIAGNOSTIC",
    "WANT_FULL",
    "project",
    "TrustedFrame",
    "Repair",
    "ProblemContext",
    # event bus + taxonomy + projections + sinks + codec
    "EventBus",
    "SubscriberFailure",
    "SessionStore",
    "SessionState",
    "MemoryEventSink",
    "events",
    "ALLOWED_EVENT_FILTERS",
    "allowed_filters",
    "register_event_filter",
    "event_matches",
    "validate_filter",
    "event_digest",
    "link",
    "verify_chain",
    "chain_head",
    "verify_against_anchor",
    "IdentityCodec",
    "PayloadCodec",
    "KeyProvider",
    "encode_payload",
    "decode_payload",
    "SecurityBlock",
    "scope_event",
    "scope_payload",
    "RENDER_KEYS",
    # ZU-RAIL-8 — restore-to-last-known-good rollback (public primitive)
    "mark_checkpoint",
    "last_known_good",
    "rollback_and_replan",
    "CHECKPOINT_MARKED",
    "RUN_ROLLED_BACK",
    # standalone monitor folding (#38) + handle-free no-op oracle
    "run_monitors",
    "evaluate_invariants",
    "is_noop",
    "surface_diff",
    # content_view + escalation event taxonomy (Issue #41)
    "CONTENT_CAPTURED",
    "STEP_ESCALATED",
    "STEP_REPAIRED",
    # ports
    "CAP_NET",
    "CAP_SANDBOX",
    "CAP_FS_READ",
    "CAP_FS_WRITE",
    "CAP_SUBPROCESS",
    "EGRESS_OPEN",
    "INTERFACE_VERSION",
    "INTERFACE_ATTR",
    "declared_envelope",
    "CapScope",
    "Capabilities",
    "Candidate",
    "Channel",
    "ChannelRequest",
    "ChannelResponse",
    "Consent",
    "CredentialBroker",
    "Detector",
    "EgressEnforcement",
    "EventSink",
    "ExecutionLedger",
    "Finish",
    "Grant",
    "GrantStore",
    "IdentityProof",
    "Instrument",
    "InvocationGate",
    "ModelProvider",
    "ModelRequest",
    "ModelResponse",
    "Policy",
    "ReplayArbiter",
    "ReplayDecision",
    "ReputationProvider",
    "ReputationVerdict",
    "RetrievalProvider",
    "RetrievalQuery",
    "RunContext",
    "SandboxBackend",
    "Scope",
    "Severity",
    "Tool",
    "ToolCall",
    "ToolSpec",
    "Trigger",
    "TriggerEvent",
    "UseOutcome",
    "UseRequest",
    "Validator",
    "Verdict",
    "WorkloadIdentity",
    # registry
    "REGISTRY",
    "LoadFailure",
    "IncompatibleInterfaceError",
    "KindSpec",
    "check_interface",
    "kind_decorator",
    "Registry",
    "arbiter",
    "backend",
    "channel",
    "credential_broker",
    "detector",
    "gate",
    "policy",
    "provider",
    "reputation_provider",
    "retrieval_provider",
    "sink",
    "tool",
    "trigger",
    "validator",
]
