"""Zu core — the small, stable runtime: contracts, ports, registry, loop, bus.

Depends only on the standard library and Pydantic. It contains no model SDK,
no domain branching, and no knowledge of any specific tool or provider.
"""

from __future__ import annotations

from . import events
from .bus import EventBus, SubscriberFailure
from .chain import chain_head, event_digest, link, verify_against_anchor, verify_chain
from .codec import IdentityCodec, KeyProvider, PayloadCodec, decode_payload, encode_payload
from .content import Action, Audio, Content, ContentPart, Image, Observation, Text
from .contracts import Budget, Event, Result, Status, TaskSpec
from .eventstore import (
    ALLOWED_EVENT_FILTERS,
    allowed_filters,
    event_matches,
    register_event_filter,
    validate_filter,
)
from .ports import (
    CAP_FS_READ,
    CAP_FS_WRITE,
    CAP_NET,
    CAP_SANDBOX,
    CAP_SUBPROCESS,
    EGRESS_OPEN,
    INTERFACE_ATTR,
    INTERFACE_VERSION,
    Capabilities,
    Channel,
    ChannelRequest,
    ChannelResponse,
    Detector,
    EgressEnforcement,
    EventSink,
    ExecutionLedger,
    Finish,
    GrantStore,
    IdentityProof,
    InvocationGate,
    ModelProvider,
    ModelRequest,
    ModelResponse,
    Policy,
    ReplayArbiter,
    ReplayDecision,
    RunContext,
    SandboxBackend,
    Scope,
    Severity,
    Tool,
    ToolCall,
    ToolSpec,
    Trigger,
    TriggerEvent,
    Validator,
    Verdict,
    WorkloadIdentity,
    declared_envelope,
)
from .projections import SessionState, SessionStore
from .registry import (
    REGISTRY,
    IncompatibleInterfaceError,
    KindSpec,
    LoadFailure,
    Registry,
    arbiter,
    backend,
    channel,
    check_interface,
    detector,
    gate,
    kind_decorator,
    policy,
    provider,
    sink,
    tool,
    trigger,
    validator,
)
from .security import SecurityBlock
from .sinks import MemoryEventSink
from .view import RENDER_KEYS, scope_event, scope_payload

__all__ = [
    # contracts
    "Budget",
    "Event",
    "Result",
    "Status",
    "TaskSpec",
    # multimodal content (the policy currency)
    "Content",
    "ContentPart",
    "Text",
    "Image",
    "Audio",
    "Observation",
    "Action",
    # event bus + taxonomy + projections + sinks + codec
    "EventBus",
    "SubscriberFailure",
    "SessionStore",
    "SessionState",
    "MemoryEventSink",
    "events",
    "ALLOWED_EVENT_FILTERS",
    "allowed_filters",
    "register_event_filter",
    "event_matches",
    "validate_filter",
    "event_digest",
    "link",
    "verify_chain",
    "chain_head",
    "verify_against_anchor",
    "IdentityCodec",
    "PayloadCodec",
    "KeyProvider",
    "encode_payload",
    "decode_payload",
    "SecurityBlock",
    "scope_event",
    "scope_payload",
    "RENDER_KEYS",
    # ports
    "CAP_NET",
    "CAP_SANDBOX",
    "CAP_FS_READ",
    "CAP_FS_WRITE",
    "CAP_SUBPROCESS",
    "EGRESS_OPEN",
    "INTERFACE_VERSION",
    "INTERFACE_ATTR",
    "declared_envelope",
    "Capabilities",
    "Channel",
    "ChannelRequest",
    "ChannelResponse",
    "Detector",
    "EgressEnforcement",
    "EventSink",
    "ExecutionLedger",
    "Finish",
    "GrantStore",
    "IdentityProof",
    "InvocationGate",
    "ModelProvider",
    "ModelRequest",
    "ModelResponse",
    "Policy",
    "ReplayArbiter",
    "ReplayDecision",
    "RunContext",
    "SandboxBackend",
    "Scope",
    "Severity",
    "Tool",
    "ToolCall",
    "ToolSpec",
    "Trigger",
    "TriggerEvent",
    "Validator",
    "Verdict",
    "WorkloadIdentity",
    # registry
    "REGISTRY",
    "LoadFailure",
    "IncompatibleInterfaceError",
    "KindSpec",
    "check_interface",
    "kind_decorator",
    "Registry",
    "arbiter",
    "backend",
    "channel",
    "detector",
    "gate",
    "policy",
    "provider",
    "sink",
    "tool",
    "trigger",
    "validator",
]
